package com.gmb.madridshops.util

val EXTRA_SELECTED_ENTITY = "EXTRA_SELECTED_ENTITY"
val DEFAULT_MADRID_LATIDUDE = 40.4167
val DEFAULT_MADRID_LONGITUDE = -3.70325
val SUCCESS = "SUCCESS"
val ERROR = "ERROR"

