package com.gmb.madridshops.util.`fun`

val quotes = arrayOf("Apiticaaaan, apiticandemorenau",
        "¡Pecador!",
        "¿Te dah cuen?",
        "¡Fistro!",
        "Quietorr",
        "¡Pecador de la praderar!",
        "¡No puedor, no puedor!",
        "¡No te digo trigo por no llamarte Rodrigo!",
        "¡Duodeno sersuá!",
        "¿Cómorr?",
        "¡Hombre malo, violento!",
        "Norrl",
        "¡Fuegorrrl!",
        "¡Aguaaa, aguaaa!",
        "Ere un fistro diodenarl",
        "¡Hijoputarrl!",
        "¡A candemor e narrr!",
        "¡Cobarde!",
        "¡Al ataquerrrr!",
        "¡Me cago en tu muela!",
        "Meretérica, Cantando: \"Sieteee caballo que vienennn de Bonanzaaarrlll\"",
        "¡Jarl!",
        "¡Que lo sepas!",
        "¡Hijo míoorrr!",
        "¡Hasta luego Lucasss!",
        "¡Por la gloria de mi madre!",
        "Eres más peligroso que un tiroteo en un ascensor",
        "Tengo más nervios que un filete de cinco pesetas",
        "¡Es usted un torpedo!",
        "Trabaja menos que el sastre de Tarzán",
        "Ay candemor",
        "A güán, a peich, agromenáuer",
        "¡Cuidadín, quietorl!",
        "¡Te voy a borrar el cerito sesualrllr!",
        "¡Ese fistro de animarl!",
        "¡Animale bravído!!",
        "¡Te viá cortá el fiistro dabajo!",
        "¡Uno que nació después de los dolores!",
        "¡No puée sé!",
        "¡Un diodená de persona humana!",
        "¡Un gesto de hombre malo de la pradera!",
        "Se mueve uhté mah que los precioh!",
        "¡Relájese usterl!",
        "Relájate físicamente, moralmente",
        "Lo maté en agosto, la calóh apretaba",
        "En vez del graduado escolar tenía una etiqueta de Anís del Mono",
        "¡Soy cinturón negro karateca!")